{{- if .Values.webUI.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bison.webUI.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bison.labels" . | nindent 4 }}
    app.kubernetes.io/component: web-ui
spec:
  replicas: {{ .Values.webUI.replicaCount }}
  selector:
    matchLabels:
      {{- include "bison.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web-ui
  template:
    metadata:
      labels:
        {{- include "bison.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: web-ui
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: web
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ include "bison.imageRegistry" . }}{{ .Values.webUI.image.repository }}:{{ .Values.webUI.image.tag }}"
          imagePullPolicy: {{ .Values.webUI.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: API_BASE_URL
              value: "http://{{ include "bison.apiServer.fullname" . }}:{{ .Values.apiServer.service.port }}"
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.webUI.resources | nindent 12 }}
      {{- with .Values.webUI.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webUI.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webUI.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}

