{{- if and .Values.webUI.enabled .Values.webUI.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "bison.webUI.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bison.labels" . | nindent 4 }}
    app.kubernetes.io/component: web-ui
  {{- with .Values.webUI.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.webUI.ingress.className }}
  ingressClassName: {{ .Values.webUI.ingress.className }}
  {{- end }}
  {{- if .Values.webUI.ingress.tls }}
  tls:
    {{- range .Values.webUI.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.webUI.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "bison.webUI.fullname" . }}
                port:
                  number: {{ .Values.webUI.service.port }}
{{- end }}

