{{- if .Values.webUI.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bison.webUI.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bison.labels" . | nindent 4 }}
    app.kubernetes.io/component: web-ui
spec:
  type: {{ .Values.webUI.service.type }}
  ports:
    - port: {{ .Values.webUI.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "bison.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web-ui
{{- end }}

